theme: jekyll-theme-hacker
markdown: kramdown

# 카테고리 페이지 생성을 위한 설정
permalink: pretty
baseurl: "/external-blog"
collections:
  posts:
    output: true

# 태그/카테고리 목록 페이지를 위해 플러그인 설정
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
